# Generated by Django 3.1 on 2020-08-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navers', '0001_initial'),
        ('projects', '0004_auto_20200815_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='navers',
            field=models.ManyToManyField(to='navers.Navers'),
        ),
    ]
