# Generated by Django 3.1 on 2020-08-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_projects_navers'),
        ('navers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navers',
            name='projects',
            field=models.ManyToManyField(to='projects.Projects'),
        ),
    ]
