# Generated by Django 3.1 on 2020-08-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_projects_navers'),
        ('navers', '0002_navers_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navers',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='projects.Projects'),
        ),
    ]
